version: '${COMPOSE_VERSION}'

services:
  zbx-db:
    image: ${REGISTER}/mysql:${MYSQL_TAG}
    container_name: zbx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_ZBX_USER}
      MYSQL_PASSWORD: ${MYSQL_ZBX_PWD}
    restart: always
    ports:
      - "3303:3306"

  zbx-proxy:
    image: zabbix/zabbix-proxy-mysql:${ZBX_TAG}
    container_name: zbx-proxy
    depends_on:
      - zbx-mysql
    environment:
      DB_SERVER_HOST: ${ZBX_DB_SERVER}
      DB_SERVER_PORT: ${ZBX_DB_PORT}
      MYSQL_USER: ${ZBX_DB_USER}
      MYSQL_PASSWORD: ${ZBX_DB_PWD}
      ZBX_HOSTNAME: ${HOSTNAME}
      ZBX_SERVER_HOST: ${ZBX_SERVER}
    restart: always
    ports:
      - "10051:10051"

